<x-guest>

    <div class="pt-8 mx-auto bg-white max-w-7xl">
        <div class="overflow-hidden bg-white shadow-sm sm:rounded-lg">
            <div class="pl-20">
                <img src="{{ asset('images/upcoming.jpg') }}" alt="">
            </div>

            <div class="p-6 bg-white border-b border-gray-200">
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16">Yellow puppies expected. Also, possibility of a young adult available to the right home. </p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">Below is information on our current availability and also on our current Covid prevention measures. Please read the information below in its entirety.</p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">We finally are getting caught up on the frenzy caused by the Covid pandemic. Two litters born early in 2022 allowed us to fulfill several of our reservations. We hope to be expecting yellow puppies to be born mid June, 2022 and they will be expected to go to their homes early July. We are screening homes and accepting deposits for this litter currently. Now that we are largely caught up with our waiting list, wait times and upcoming plans will be far easier to manage and predict. </p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">Like many reputable Breeders, we continue to receive inquiries on a daily basis. With Covid, screening the homes is difficult, more time consuming and requires telephone and other electronic means, rather than the family room visits of yesteryear. Returning Staghorn families and their family members and friends are wherever possible, prioritized. That is not to say we will not welcome new inquiries. Folks wishing to contact us with a view to being placed on our waiting list need to contact us earlier, rather than later. If you are looking for a puppy today or tomorrow, it’s unlikely that I or any of my colleague Breeders will have a puppy available on short notice. The preferred method to be included to our waiting list is that you begin by emailing us through our website to initiate contact, versus calling. Thanks, and I look forward to hearing from committed families who are patient and understand the process will not result in an immediate puppy.</p>
                <div class="flex justify-center py-4 no-wrap ">
                    <div><img src="{{ asset('images/tia8022.jpg') }}" class="px-2" alt="Staghorn Puppies"></div>
                    <div><img src="{{ asset('images/puppies7802.jpg') }}" class="px-2"  alt="Staghorn Puppies"></div>
                </div>

                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">All our breeding stock are OFA certified free and clear of hip/elbow dysplasia and eye cleared annually by a qualified canine opthalmogist, to have normal eyes, and/or to have no evidence of conditions which are suspected to be inherited. We also invest in genetic testing, to assure that we are selectively breeding parents who will not produce PRCD PRA, a genetically recessive, blinding eye disease. We also do many other genetic tests, on the Labrador Panels at the major genetic testing facilities in the USA. This includes testing to confirm that our dogs do NOT carry the dilute (foreign to our breed) gene that came from Weimarainers and results in non accepted, non breed standard, incorrect colours. Many unscrupulous breeders name these colours catchy names such as silver, charcoal, champagne, and even white. Thankfully, most members of the public are smart enough to recognize this sham, don’t be a victim to it. If you have any further questions about colour in Labs, please ask. I will put on my hat as President of the Eastern Ontario Labrador Breeder’s Association, or as a Life member of the Labrador Retriever Club of Canada, when answering those questions. </p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">All of our males and most of our females also have cardiac clearances (ECHO doppler ultrasounds of the heart). Ontario has always been underserviced in terms of access to these specialized cardiac services, and it has been even worse during Covid. I myself have had to organize clinics myself and bring in Board Certified Cardiologists to get my own dogs done. </p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">We encourage puppy buyers who are looking to adopt a new member of their family, (one that will hopefully be healthy - both physically and psychologically) to inspect such health certificates and to ask questions of the Breeder, in order to assure yourself that you are dealing with a well educated Breeder who has a solid working understanding of the official breed standard, who knows the possible health issues in their breed and the risk factors related to them, (each breed can have them.) Also look for a Breeder who you feel can communicate with you in a fashion that will ensure years of comfortable and intelligent communication, especially should any issues arise that require you both to walk hand in hand together, for the benefit of your puppy. While I can provide numerous references from folks who have not experienced any problems with their Staghorn dogs, I can also provide references from people who contacted me regarding a problem and who were very satisfied with how I handled it and who continue to this day, to refer friends and family to me. </p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">Regarding Covid, we normally encourage folks to ensure that you are able to visit the parents and other relatives to the upcoming puppies. Sometimes the sire is not onsite, but sometimes he is. However, in these Covid times, one cannot always expect a Breeder to literally open their home up to the public. I myself take an immunosuppressant drug that can compromise my immune system’s ability to respond. Thus, in these very trying times, I recommend that you use other means to satisfy yourself that you are dealing with a reputable Breeder. I mainly use emails and telephone calls as my primary means of communication. I have participated in a few Zoom kennel club meetings but I am the first to tell you that this old Breeder is not technologically inclined. I wouldn’t have a clue how to walk through my house doing livestream filming of my dogs/puppies. Since Covid arrived, there have been no in-person visits and all paperwork etc. is done up in advance and our handovers of the puppy to the new homes have been very carefully organized, either outdoors or using an outbuilding, and including masks, hand sanitizer and social distancing. I have always used the information provided by the family, in advance, to choose which puppy goes to which home, based on my careful observations and matching the qualities and traits of the puppy to the activities and lifestyle of the family. That is not new and has been my practice since long before Covid “was a thing”. If these measures are not acceptable to you then I need to be clear that Staghorn is not the place for you to purchase a puppy at this time.</p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">Again, most of my clients are returning families including the now grown and married children who came here when they were mere toddlers themselves. We had a drone photographer come and take pictures of our property and my husband has tried to capture the essence of our home and our dog’s lives, on our website. Regardless of your method of communication, it’s still possible that you ask questions to get a feel for the Breeder’s investment in their facilities and breeding program, and to determine whether or not you feel the Breeder is dedicated to their Labradors and will be around in several years, or whether they have the facilities to take back any dog that they have brought into this world, should the dog's buyer not be able to keep it.<strong> A reputable Breeder takes full responsibility for the LIFETIME of the dogs they breed, and they will NOT burden the Humane Societies or rescue shelters with their dogs</strong>.</p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">All Staghorn puppies are sold on a CKC Non Breeding registration and the buyer enters a written agreement that pets must be spayed or neutered at the agreed upon and recommended age. We encourage families who have bought puppies from us to keep in touch, send pictures and notes about their pups. This helps us with future breeding decisions.</p>
                <p class="px-4 pt-4 mx-auto prose-xl prose-p lg:px-16 ">And finally, a brief note about deposits. A deposit is a commitment on both parties' part. If I accept a deposit from you, I am placing you on a list of folks to whom I am committed. I remain committed to the group I am working with to provide a puppy within reasonable, given timeframes. I turn aways folks who come after a certain number of deposits are received and often refer them to a colleague Breeder. If for any reason on MY part, I cannot provide you with a puppy reasonably near the time frames discussed, I will happily return your deposit and will assist you to find a suitably well bred Labrador from a colleague. A deposit is not something to leave with several Breeders and then take the first puppy that comes along. Should you do so, expect to forfeit the deposit, the same as with any other purchase</p>

            </div>
        </div>
    </div>
</x-guest>
